server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost/devcon
    username: devcon
    password: password
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/auth/realms/devcon
          jwk-set-uri: http://localhost:8083/auth/realms/devcon/protocol/openid-connect/certs
