server:
  port: 8080
  servlet:
    session:
      cookie:
        name: UI2SESSION

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: jwtClient
            client-secret: jwtClientSecret
            authorization-grant-type: authorization_code
            scope: openid
            client-name: jwtClient
        provider:
          keycloak:
            issuer-uri: http://localhost:8083/auth/realms/devcon
            user-name-attribute: preferred_username